// server/typeDb.test.ts
// The zip reader, the table, the category rules and TypeDb's loading, on zips built here and a fake fetch on a fake
// clock. Nothing here touches the network. The aircraft are real entries of the Mictronics files (2026-09-27): YR-ADA,
// 4X-EKA, a Robinson R44, a Cessna 172, a ground vehicle and a tower at Frankfurt, a Zeppelin NT.
import { test } from 'node:test'
import assert from 'node:assert/strict'
import { setTimeout as sleep } from 'node:timers/promises'
import { TypeDb, buildTypeTable, categoryOf, encodeZip, readZip } from './typeDb.ts'

const bytes = (s: string): Uint8Array => new TextEncoder().encode(s)
const text = (b: Uint8Array | undefined): string => new TextDecoder().decode(b)
const HOUR = 3_600_000
const MIN = 60_000

// ---- readZip ----

test('readZip: stored and deflated entries come back as they were, by name', async () => {
  const types = '{"A320":{"desc":"L2J","wtc":"M"},"B738":{"desc":"L2J","wtc":"M"},"R44":{"desc":"H1P","wtc":"L"}}'
  const zip = encodeZip([
    { name: 'dbversion.json', data: bytes('{"version":524\n}'), method: 0 },
    { name: 'types.json', data: bytes(types), method: 8 },
    { name: 'empty.json', data: new Uint8Array(0), method: 8 },
  ])
  const files = await readZip(zip)
  assert.deepEqual([...files.keys()], ['dbversion.json', 'types.json', 'empty.json'])
  assert.equal(text(files.get('dbversion.json')), '{"version":524\n}')
  assert.equal(text(files.get('types.json')), types)
  assert.equal(files.get('empty.json')?.length, 0)
})

test('readZip: an archive comment after the end record, and a local header with its own extra field', async () => {
  // The real zip ends with "Generated by Mictronics. 27.09.2026 Made available under the Open Data Commons Attribution License."
  const comment = 'Generated by Mictronics. 27.09.2026 Made available under the Open Data Commons Attribution License.'
  const zip = encodeZip([{ name: 'a.json', data: bytes('[1,2,3]'), method: 8, localExtra: 28 }, { name: 'b.json', data: bytes('{}'), method: 0, localExtra: 9 }], comment)
  const files = await readZip(zip)
  assert.equal(text(files.get('a.json')), '[1,2,3]')
  assert.equal(text(files.get('b.json')), '{}')
})

test("readZip: a zip written by Info-ZIP's zip 3.0 (macOS): extended-timestamp fields of other lengths in the local and central headers, a comment", async () => {
  // `zip -0 t.zip dbversion.json; zip t.zip types.json; zip -z t.zip`, 447 bytes: local extra 28 bytes, central 24.
  const zip = new Uint8Array(Buffer.from(
    '504b03040a0000000000f473425d7a96d5b510000000100000000e001c00646276657273696f6e2e6a736f6e55540900031c96bf6a1c96bf6a75780b000104f5' +
    '01000004000000007b2276657273696f6e223a3532340a7d504b0304140000000800f473425dd88d50462a000000610000000a001c0074797065732e6a736f6e' +
    '55540900031c96bf6a1c96bf6a75780b000104f50100000400000000ab567234363250b2aa564a492d4e56b252f231f252d2512a2f01b17d956a7540f28604e4' +
    '8d70cbd70200504b01021e030a0000000000f473425d7a96d5b510000000100000000e0018000000000000000000a48100000000646276657273696f6e2e6a73' +
    '6f6e55540500031c96bf6a75780b000104f50100000400000000504b01021e03140000000800f473425dd88d50462a000000610000000a001800000000000100' +
    '0000a4815800000074797065732e6a736f6e55540500031c96bf6a75780b000104f50100000400000000504b05060000000002000200a4000000c60000003f00' +
    '4d61646520617661696c61626c6520756e64657220746865204f70656e204461746120436f6d6d6f6e73204174747269627574696f6e204c6963656e73652e',
    'hex',
  ))
  const files = await readZip(zip)
  assert.equal(text(files.get('dbversion.json')), '{"version":524\n}')
  assert.equal(text(files.get('types.json')), '{"A320":{"desc":"L2J","wtc":"M"},"A321":{"desc":"L2J","wtc":"M"},"A322":{"desc":"L2J","wtc":"M"}}')
})

/** A zip whose second entry claims method 99 in its central directory. */
function zipWithMethod99(): Uint8Array {
  const zip = encodeZip([{ name: 'types.json', data: bytes('{}'), method: 8 }, { name: 'odd.bin', data: bytes('xyz'), method: 0 }])
  const dv = new DataView(zip.buffer)
  let o = zip.length - 22
  o = dv.getUint32(o + 16, true) // the central directory
  o += 46 + dv.getUint16(o + 28, true) // past the first entry
  dv.setUint16(o + 10, 99, true)
  return zip
}

test('readZip: `want` reads only the entries named; the others are skipped unread, a method it cannot read included', async () => {
  const zip = zipWithMethod99()
  assert.deepEqual([...(await readZip(zip, new Set(['types.json']))).keys()], ['types.json'])
  await assert.rejects(readZip(zip), /odd\.bin uses method 99/)
})

test('readZip: what is not a whole, sound zip throws', async () => {
  const good = encodeZip([{ name: 'aircrafts.json', data: bytes('{"4A0481":{"t":"A320"}}'), method: 8 }])
  await assert.rejects(readZip(new Uint8Array(0)), /no end of central directory/)
  await assert.rejects(readZip(bytes('<html><body>404 Not Found</body></html>')), /no end of central directory/)
  await assert.rejects(readZip(good.subarray(0, good.length - 10)), /no end of central directory/, 'the end cut off')
  await assert.rejects(readZip(good.subarray(10)), /no central directory entry/, 'the start cut off: the offsets miss')
  const flipped = good.slice()
  flipped[30 + 'aircrafts.json'.length + 1] ^= 0xff // a byte of the deflated data
  await assert.rejects(readZip(flipped))
  const stored = encodeZip([{ name: 'types.json', data: bytes('{"A320":{}}'), method: 0 }])
  stored[30 + 'types.json'.length + 2] ^= 0x01 // a byte of the stored data: the CRC no longer matches
  await assert.rejects(readZip(stored), /does not match its size or CRC/)
})

// ---- the category rules ----

test('categoryOf: every rule, in its order, with real types', () => {
  const cases: [string, string, string, string][] = [
    // by name: surface vehicles, a tower, gliders, lighter-than-air, ultralights (the brief's five, then the rest of their kind)
    ['GND', 'V0-', '-', 'C2'], ['TWR', 'T0-', '-', 'C3'], ['GLID', 'L0-', '-', 'B1'], ['BALL', 'B0-', '-', 'B2'], ['ULAC', 'L0-', '-', 'B4'],
    ['SERV', 'V0-', '-', 'C2'], ['EMER', 'V0-', '-', 'C1'], ['GLIM', 'L1M', 'L', 'B1'], ['SHIP', 'B0-', '-', 'B2'], ['PARA', 'P0-', '-', 'B4'],
    // helicopter, gyrocopter, tiltrotor (ICAO's T; this table's R): before the wake
    ['R44', 'H1P', 'L', 'A7'], ['H60', 'H2T', 'M', 'A7'], ['MI26', 'H2T', 'H', 'A7'], ['UHEL', 'H0-', '-', 'A7'],
    ['GYRO', 'G0-', '-', 'A7'], ['A002', 'G1P', 'L', 'A7'], ['V22', 'R2T', 'M', 'A7'], ['B609', 'R2T', 'M', 'A7'], ['XTLT', 'T2T', 'M', 'A7'],
    ['DRON', 'D0-', '-', 'B6'], ['VFHC', 'D0-', '-', 'B6'],
    // heavy or super wake, before the engines
    ['A388', 'L4J', 'H', 'A5'], ['B744', 'L4J', 'H', 'A5'], ['A400', 'L4T', 'H', 'A5'], ['XSUP', 'L4J', 'J', 'A5'],
    // piston, turboprop, electric
    ['C172', 'L1P', 'L', 'A1'], ['DA42', 'L2P', 'L', 'A1'], ['AT76', 'L2T', 'M', 'A1'], ['C130', 'L4T', 'M', 'A1'], ['A1P', 'A1P', 'L', 'A1'], ['PIVE', 'L1E', 'L', 'A1'],
    // any other
    ['A320', 'L2J', 'M', 'A3'], ['B738', 'L2J', 'M', 'A3'], ['F16', 'L1J', 'M', 'A3'], ['SS2', 'L1R', 'L', 'A3'], ['ODD', '', '', 'A3'],
  ]
  for (const [type, desc, wtc, want] of cases) assert.equal(categoryOf(type, desc, wtc), want, `${type} ${desc} ${wtc}`)
})

// ---- the table ----

const AIRCRAFT = {
  '4A0481': { r: 'YR-ADA', t: 'A320', f: '00', d: 'AIRBUS A-320' },
  '738063': { r: '4X-EKA', t: 'B738', f: '00', d: 'BOEING 737-800' },
  '00830B': { r: 'ZS-HIE', t: 'R44', f: '00', d: 'ROBINSON R-44 Raven' },
  A00018: { r: 'N1AX', t: 'C172', f: '00', d: 'CESSNA 172 Skyhawk' },
  '109866': { r: 'GND', t: 'GND', f: '00', d: '' },
  '106593': { r: 'TWR', t: 'TWR', f: '00', d: '' },
  '3F232B': { r: 'D-LZFN', t: 'SHIP', f: '00', d: 'Zeppelin LZ N07-101' },
  '142635': { r: '09781', t: '', f: '00', d: '' }, // no type: not kept
  '386426': { r: 'F-AZBG', t: 'ZZZZ', f: '00', d: 'SFCA PEYRET TAUPIN TYPE VI' }, // ICAO's "no designator": not kept
  '4B1234': { r: 'HB-XXX', t: 'NEW1', f: '00', d: '' }, // a type types.json does not describe: a type, no category
}
const TYPES = {
  A320: { desc: 'L2J', wtc: 'M' }, B738: { desc: 'L2J', wtc: 'M' }, R44: { desc: 'H1P', wtc: 'L' }, C172: { desc: 'L1P', wtc: 'L' },
  GND: { desc: 'V0-', wtc: '-' }, TWR: { desc: 'T0-', wtc: '-' }, SHIP: { desc: 'B0-', wtc: '-' }, ZZZZ: { desc: '-0-', wtc: '-' },
}
const tableDb = (aircraft: unknown = AIRCRAFT, types: unknown = TYPES): TypeDb => new TypeDb({ userAgent: 't', table: buildTypeTable(aircraft, types) })

test('buildTypeTable: the typed addresses sorted, one type index each; per type its designator and category', () => {
  const t = buildTypeTable(AIRCRAFT, TYPES)
  assert.deepEqual([...t.addrs].map((a) => a.toString(16).padStart(6, '0')), ['00830b', '106593', '109866', '3f232b', '4a0481', '4b1234', '738063', 'a00018'])
  assert.deepEqual([...t.typeOf].map((i) => t.codes[i]), ['R44', 'TWR', 'GND', 'SHIP', 'A320', 'NEW1', 'B738', 'C172'])
  assert.equal(new Set(t.codes).size, t.codes.length, 'each type once')
  assert.equal(t.cats.length, t.codes.length)
})

test('type and category: a hit in either case, a miss, a ~ address and what is no address are null', () => {
  const db = tableDb()
  assert.deepEqual([db.type('4a0481'), db.category('4a0481')], ['A320', 'A3'])
  assert.deepEqual([db.type('4A0481'), db.category('4A0481')], ['A320', 'A3'])
  assert.deepEqual([db.type('738063'), db.type('00830b'), db.type('a00018'), db.type('109866'), db.type('106593'), db.type('3f232b')], ['B738', 'R44', 'C172', 'GND', 'TWR', 'SHIP'])
  assert.deepEqual([db.category('738063'), db.category('00830b'), db.category('a00018'), db.category('109866'), db.category('106593'), db.category('3f232b')], ['A3', 'A7', 'A1', 'C2', 'C3', 'B2'])
  assert.deepEqual([db.type('4b1234'), db.category('4b1234')], ['NEW1', null], 'a type with no description: no category')
  for (const hex of ['ffffff', '000000', '142635', '386426', '~4a0481', '~abc123', '4a048', '4a04811', 'xyzxyz', '', ' 4a0481']) {
    assert.deepEqual([db.type(hex), db.category(hex)], [null, null], JSON.stringify(hex))
  }
  assert.deepEqual([new TypeDb({ userAgent: 't' }).type('4a0481'), new TypeDb({ userAgent: 't' }).category('4a0481')], [null, null], 'no table yet')
})

test('buildTypeTable: what is not an address with a designator is left out; one address twice is kept once; junk is an empty table', () => {
  const t = buildTypeTable({ '4a0481': { t: 'A320' }, '4A0481': { t: 'A20N' }, '73806': { t: 'B738' }, '7380630': { t: 'B738' }, '~abc123': { t: 'B738' }, '738063': { t: 'b738' }, '738064': { t: 'B7380' }, '738065': null, '738066': 'B738', '738067': { t: 7 } }, TYPES)
  assert.deepEqual([...t.addrs], [0x4a0481])
  assert.deepEqual(t.codes.length, 2)
  for (const junk of [null, undefined, 'x', 42, [], [{ t: 'A320' }]]) assert.equal(buildTypeTable(junk, TYPES).addrs.length, 0, JSON.stringify(junk))
  assert.equal(buildTypeTable(AIRCRAFT, null).cats.every((c) => c === 0), true, 'no types.json: types, no categories')
})

// ---- TypeDb: a fake host on a fake clock ----

const zipOf = (aircraft: unknown, types: unknown = TYPES): Uint8Array<ArrayBuffer> =>
  encodeZip([
    { name: 'dbversion.json', data: bytes('{"version":524\n}'), method: 0 },
    { name: 'types.json', data: bytes(JSON.stringify(types)), method: 8 },
    { name: 'aircrafts.json', data: bytes(JSON.stringify(aircraft)), method: 8 },
  ])

type Answer = Response | Error | Promise<Response>
/** A TypeDb on a fake host that gives `first`, then whatever next() sets (a Response is read once: set a new one per call). */
function host(first: Answer) {
  let answer = first
  const calls: { url: string; headers: Headers; signal: AbortSignal | null | undefined }[] = []
  const fetchFn = (async (url: string, init?: RequestInit) => {
    calls.push({ url, headers: new Headers(init?.headers), signal: init?.signal })
    if (answer instanceof Error) throw answer
    return answer
  }) as unknown as typeof fetch
  const clock = { t: Date.UTC(2026, 9, 2, 12) }
  const db = new TypeDb({ userAgent: 'FlightHopper-test', fetchFn, nowMs: () => clock.t })
  return { db, calls, clock, next: (a: Answer) => void (answer = a) }
}
const zipResponse = (aircraft: unknown, etag = '"v1"', types: unknown = TYPES): Response => new Response(zipOf(aircraft, types), { status: 200, headers: { etag } })

test('load: from Mictronics on GitHub, with the user agent and a time limit; the table is in after it', async () => {
  const { db, calls } = host(zipResponse(AIRCRAFT))
  assert.equal(await db.load(), true)
  assert.deepEqual(calls.map((c) => c.url), ['https://raw.githubusercontent.com/Mictronics/aircraft-database/main/indexedDB_old.zip'])
  assert.equal(calls[0].headers.get('user-agent'), 'FlightHopper-test')
  assert.equal(calls[0].headers.get('if-none-match'), null, 'the first is not conditional')
  assert.ok(calls[0].signal instanceof AbortSignal && !calls[0].signal.aborted, 'a stuck download ends by itself')
  assert.deepEqual([db.type('4a0481'), db.category('00830b')], ['A320', 'A7'])
})

test('load: conditional after the first; a 304 keeps the table; a new zip replaces it whole', async () => {
  const { db, calls, next } = host(zipResponse(AIRCRAFT, '"v1"'))
  await db.load()
  next(new Response(null, { status: 304 }))
  assert.equal(await db.load(), true)
  assert.equal(calls[1].headers.get('if-none-match'), '"v1"')
  assert.equal(db.type('4a0481'), 'A320', 'kept')
  next(zipResponse({ '738063': { t: 'B38M' } }, '"v2"'))
  assert.equal(await db.load(), true)
  assert.deepEqual([db.type('738063'), db.type('4a0481')], ['B38M', null], 'the new table only')
  next(new Response(null, { status: 304 }))
  await db.load()
  assert.equal(calls[3].headers.get('if-none-match'), '"v2"')
})

test('load: a failure keeps the old table: a bad status, a network error, a timeout, junk, a zip without the files, JSON that is not, no typed address', async () => {
  const { db, next } = host(zipResponse(AIRCRAFT))
  await db.load()
  const failures: [string, Answer][] = [
    ['500', new Response('Server Error', { status: 500 })],
    ['404', new Response('Not Found', { status: 404 })],
    ['network', new Error('ECONNRESET')],
    ['timeout', new DOMException('The operation was aborted due to timeout', 'TimeoutError')],
    ['html', new Response('<html>rate limited</html>', { status: 200 })],
    ['no aircrafts.json', new Response(encodeZip([{ name: 'types.json', data: bytes('{}'), method: 8 }]), { status: 200 })],
    ['not JSON', new Response(encodeZip([{ name: 'aircrafts.json', data: bytes('{"4A0481":'), method: 8 }, { name: 'types.json', data: bytes('{}'), method: 0 }]), { status: 200 })],
    ['no type in it', zipResponse({ '4A0481': { r: 'YR-ADA', t: '' } })],
  ]
  for (const [what, answer] of failures) {
    next(answer)
    assert.equal(await db.load(), false, what)
    assert.equal(db.type('4a0481'), 'A320', `${what}: the old table stays`)
  }
  const fresh = host(new Error('ECONNREFUSED'))
  assert.equal(await fresh.db.load(), false)
  assert.equal(fresh.db.type('4a0481'), null, 'no table yet, none after')
})

test('load: calls during a download share it', async () => {
  let release!: (r: Response) => void
  const { db, calls } = host(new Promise<Response>((r) => (release = r)))
  const both = Promise.all([db.load(), db.load()])
  release(zipResponse(AIRCRAFT))
  assert.deepEqual(await both, [true, true])
  assert.equal(calls.length, 1)
})

test('tick: loads at once, again a day after a good load, 10 minutes after a failed one, not before', async () => {
  const { db, calls, clock, next } = host(zipResponse(AIRCRAFT))
  await db.tick()
  assert.equal(calls.length, 1, 'the first tick loads')
  clock.t += 24 * HOUR - 1
  await db.tick()
  assert.equal(calls.length, 1, 'a day is not up')
  clock.t += 1
  next(new Error('ECONNRESET'))
  await db.tick()
  assert.equal(calls.length, 2, 'a day on: checked again')
  assert.equal(db.type('4a0481'), 'A320', 'it failed: the table stays')
  clock.t += 10 * MIN - 1
  await db.tick()
  assert.equal(calls.length, 2, 'retried after 10 minutes, not sooner')
  clock.t += 1
  next(new Response(null, { status: 304 }))
  await db.tick()
  assert.equal(calls.length, 3)
  assert.equal(calls[2].headers.get('if-none-match'), '"v1"')
  clock.t += 24 * HOUR - 1
  await db.tick()
  assert.equal(calls.length, 3, 'a 304 is a good load: the next a day on')
})

test('ready: true at once with a table; false after ms without one; true as soon as a load lands; never rejects', async () => {
  assert.equal(await tableDb().ready(5000), true)
  const { db } = host(new Error('ECONNRESET'))
  const t0 = performance.now()
  assert.equal(await db.ready(40), false)
  assert.ok(performance.now() - t0 >= 35, 'it waited')
  await db.load() // fails: the waiting goes on to its end, it does not reject
  assert.equal(await db.ready(20), false)

  let release!: (r: Response) => void
  const gated = host(new Promise<Response>((r) => (release = r)))
  const waits = [gated.db.ready(5000), gated.db.ready(5000)]
  const loading = gated.db.load()
  await sleep(20)
  const t1 = performance.now()
  release(zipResponse(AIRCRAFT))
  assert.deepEqual(await Promise.all(waits), [true, true])
  assert.ok(performance.now() - t1 < 1000, 'not the whole 5 s')
  assert.equal(await loading, true)
})

test('close: the download under way is aborted and fails, the table stays; nothing is asked after it', async () => {
  const signals: AbortSignal[] = []
  const fetchFn = ((_url: string, init?: RequestInit) =>
    new Promise((_resolve, reject) => {
      const signal = init!.signal!
      signals.push(signal)
      signal.addEventListener('abort', () => reject(signal.reason))
    })) as unknown as typeof fetch
  const db = new TypeDb({ userAgent: 't', fetchFn, table: buildTypeTable(AIRCRAFT, TYPES) })
  const pending = db.load()
  assert.equal(signals.length, 1)
  db.close()
  assert.equal(signals[0].aborted, true)
  assert.equal(await pending, false)
  assert.equal(db.type('4a0481'), 'A320')
  assert.equal(await db.load(), false)
  await db.tick()
  assert.equal(signals.length, 1, 'closed: nothing new is asked')
})
